### ISSUE TITLE
Create incremental update example for multi-arch Godot games

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/delta-pack#2]
# Plan

Implement a client/server system such that Godot apps in Mac, Linux/X11, and Windows can query for new versions, download the appropriate patch files, apply them, and reload the newly-generated PCK contents.

## Client implementation

We assume that the Self Update logic is the very first thing run during the Godot application's lifetime. 

The client contacts a `delta` server (see below) using HTTP, querying for updates that can be applied to the current PCK file.  It verifies all update diffs and generated PCK files by computing BLAKE2b checksums and comparing them to the expected. 

Work on signing diffs is deferred until #14.

- [x] draft godot client logic #6 

### Distributing updates to code 

This mainly affects how we pass version info from update to update.

Method defs, variables etc don't update when load_resource_pack is called - - at least not those attached to the main script. If you restart the app after the update, they work as expected. 

The solution is to use Resource.take_over_path and force a cache refresh, as in https://github.com/Terkwood/godot-script-reload-demo/blob/a6da03652fdeee1c261cf54584b2c190eaf6e07a/Main.gd#L12

- [x] create version resource and force refresh of version https://godotengine.org/qa/21370/what-are-various-ways-that-i-can-store-data?show=21371#a21371

## Multi-arch support tasks

- [x] set up basic rust bindings (#3)
- [x] setup cross compile for mac -> linux 
- [x]  build and release rust dylib on  mac , win , linux using github actions
- [x] fix bootstrapping for Windows and X11, as in #26 
- [x] fix #41  
- [x] final check   on each target platform & release rust lib via GH actions 

##  Delta (patch metadata) server

Answers request for all new version records since a given version  

For each version, Provides URL to patch diff, checksum for that diff, checksum for the expected patch

Look up the internal ID of the requested version number, and from there, you can scan for remaining patches which need to be applied.

- [x] write web server (actix-web &  sled  ) for patch lookup by public
- [x] read only, public route on webserver

## Scripting

- [x]   output  PCK deltas with `bidiff`  
- [x] compute checksums for both PCK delta and full PCK

## Planning for the future: managing  `so` and `dylib` payloads

In the future, a developer may choose to release new shared object libraries, e.g. for linking to rust / C++ / etc code.  These shared libs are not part of a PCK file distribution created by the Godot exporter.

In order to accomplish updates or additions to shared libs, we recommend writing custom Godot logic to download the library payloads individually.  

Please exercise caution, as we haven't determined the difficulty or feasibility of reloading linked libraries during a given instance of the application lifetime:  _it may be the case that the app needs to shut down completely in order to pick up changes to linked libraries._

## Chicken Scratch: Initial Notes

![IMG_20201221_054325-01](https://user-images.githubusercontent.com/38859656/102768911-e34ec600-434f-11eb-889f-d7e92497adf2.jpeg)
![IMG_20201221_054329-01](https://user-images.githubusercontent.com/38859656/102768920-e8137a00-434f-11eb-8a64-968c9dfd7f46.jpeg)
![IMG_20201221_054345-01](https://user-images.githubusercontent.com/38859656/102768931-eba70100-434f-11eb-8585-06747b0ca825.jpeg)

**Comment by Terkwood** [comment]
Doesn't really seem to work with `bidiff`.  Generating a diff for a 630MB PCK file takes... uh... 35min+ on a reasonably OK machine (4 core/8 thread)

**Comment by Terkwood** [comment]
Proceed with #8

**Comment by Terkwood** [comment]
With optimized params for the patch creation, even a 688MB input isn't so bad.

Some reccs from the bidiff README:
```text

    partitions = (num_cores - 1) (this leaves a core for bookkeeping and compression)
    chunk size = newer_size / (num_cores * k), where k is between 2 and 4;
```

Assume the new file is 688MB, and assume we have 4 cores.  Then we can accomplish this patch creation in about 160sec:

```sh
time bic diff target/App-0.1.4.pck target/App-0.1.5-example.pck /tmp/tryagain-bidiff.diff --sort-partitions 3 --scan-chunk-size 57000000
```

The partitions and chunk size parameters are important.  You absolutely must tune these to your machine, or you'll be waiting for years for the algorithm to complete!

**Comment by Terkwood** [comment]
There doesn't seem to be any way to refresh code, vars, loaded scripts, or methods referenced inside Main.gd. We had to shut down the client app completely,and restart it, to see altered method definitions execute as expected

**Comment by Terkwood** [comment]
👁‍🗨  https://github.com/GDQuest/meta/issues/10

**Comment by Terkwood** [comment]
https://user-images.githubusercontent.com/38859656/103387412-9b5b3c00-4ad1-11eb-8aac-f56bb69cee85.mp4

![delta-pack](https://user-images.githubusercontent.com/38859656/103387434-c9408080-4ad1-11eb-9249-f7d2d14b8abb.gif)

**Comment by Terkwood** [comment]
Finish up #5 and #44 next
